name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # every day
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_timezone: Asia/Jakarta

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used

          plugin_repositories: yes
          plugin_repositories_pinned: 0
          plugin_repositories_featured: steveharianto/MaiPet

          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_code: yes
